version: "1.0.7"
services:
  comics:
    container_name: comics
    image: inpiniti/comics:1.0.7
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
